### ISSUE TITLE
Where is latest repository

### ISSUE THREAD

**Issue by kurudrive** [anonymousguyx/ai1wpm-excluder#4]
At first, Thank you for your plugin.
I am using this plugin several sites.

Today I installed from dashboards and activation
but bring to this error.

```
Notice: add_submenu_page was called <strong>incorrectly</strong>. The seventh parameter passed to <code>add_submenu_page()</code> should be an integer representing menu position. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.3.0.) in /Users/kurudrive/Local Sites/sk8/app/public/wp-includes/functions.php on line 5535
```
.org plugin version is 3.0
https://wordpress.org/plugins/aio-files-excluder/

But I try this repository is no error.
but this version is 2.2

Where is latest repository?

**Comment by anonymousguyx** [comment]
@kurudrive I've updated the version to 3.0.
